fillcmd:
  use: "workflow-helm"
  short: "fill helm workflow"
  long: "uses input params to fill in a workflow"
variables:
  - name: "AZURECONTAINERREGISTRY"
    description: "the Azure container registry name"
  - name: "CONTAINERNAME"
    description: "the container image name"
  - name: "RESOURCEGROUP"
    description: "the Azure resource group of your AKS cluster"
  - name: "CLUSTERNAME"
    description: "the AKS cluster name"
  - name: "BRANCHNAME"
    description: "the Github branch to automatically deploy from"
variableDefaults:
  - name: "CHARTPATH"
    value: "./charts"
    disablePrompt: true
    description: "the charts directory path"
  - name: "CHARTOVERRIDEPATH"
    value: "./charts/production.yaml"
    disablePrompt: true
    description: "the chart override file path"
  - name: "BUILDCONTEXTPATH"
    value: "."
    description: "the build context path"